"""rename_opportunities_to_jobs_and_fix_applications_unique

Revision ID: 0001
Revises: (initial — no parent)
Create Date: 2026-05-14

WHAT THIS MIGRATION DOES
─────────────────────────
ARCH-5  Rename the main table from `opportunities` to `jobs`.
        A backwards-compatible view `opportunities` is created so that
        the Streamlit dashboard, db_sync.py, and any other legacy code
        that still says FROM opportunities keeps working without a single
        line change.  The view is a thin SELECT * wrapper — reads and
        writes pass through it transparently on Postgres 9.3+.

ARCH-7  Remove the UNIQUE(job_id) constraint that prevents a user from
        re-applying to a job after rejection, or from tracking the same
        job via different channels.  Replace it with two partial unique
        indexes that enforce the right invariants per access mode:

        idx_applications_job_id_personal
          UNIQUE on job_id WHERE user_id IS NULL
          → one application per job in single-user / personal mode.

        idx_applications_user_job_multiuser
          UNIQUE on (user_id, job_id) WHERE user_id IS NOT NULL
          → one application per (user, job) pair in multi-user mode.

        Together they preserve deduplication without blocking either
        re-apply workflows (delete first, then re-insert) or future
        multi-tenancy.

        The applications.job_id FK now points to `jobs(id)`.
        Postgres automatically updates FK target names on table rename,
        so no manual FK drop/re-add is needed here.

TRIGGER UPDATE
        The sync_application_to_opportunity trigger function (added in
        migrate_v3.py) referred to the old table name `opportunities`.
        It is recreated here pointing at `jobs` so stage changes in
        the Tracker tab continue to mirror into the legacy columns
        (applied, response_status, interview_stage) on the jobs table.

ROLLBACK
        downgrade() reverses every change: drops the view, renames the
        table back, drops the partial indexes, and restores the original
        UNIQUE constraint.
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = "0001"
down_revision: Union[str, None] = None   # first migration — no parent
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ─────────────────────────────────────────────────────────────────────────────
# UPGRADE
# ─────────────────────────────────────────────────────────────────────────────

def upgrade() -> None:
    # ── ARCH-5 step 1: rename the table ──────────────────────────────────────
    op.rename_table("opportunities", "jobs")

    # ── ARCH-5 step 2: backward-compat view for Streamlit / db_sync.py ───────
    # A Postgres updatable view — SELECT/INSERT/UPDATE/DELETE all pass through.
    # No Streamlit or legacy file needs to change.
    op.execute("""
        CREATE OR REPLACE VIEW opportunities AS
        SELECT * FROM jobs
    """)

    # ── ARCH-5 step 3: rename indexes that embedded the old table name ────────
    # (PostgreSQL auto-names indexes after the table; we clean them up so
    #  `alembic history` and pg_indexes stay readable.)
    _rename_index_if_exists("idx_opp_score",    "idx_jobs_score")
    _rename_index_if_exists("idx_opp_applied",  "idx_jobs_applied")
    _rename_index_if_exists("idx_opp_date",     "idx_jobs_date")
    _rename_index_if_exists("idx_opp_source",   "idx_jobs_source")
    _rename_index_if_exists("idx_opp_hash",     "idx_jobs_hash")
    _rename_index_if_exists("idx_opp_unscored", "idx_jobs_unscored")

    # ── ARCH-7 step 1: drop the overly-restrictive UNIQUE(job_id) ────────────
    # The constraint name is auto-generated by Postgres as
    # `applications_job_id_key` (inline UNIQUE on the column definition).
    # We guard with IF EXISTS so the migration is safe to re-run.
    op.execute("""
        DO $$
        DECLARE _cname text;
        BEGIN
            SELECT c.conname INTO _cname
            FROM   pg_constraint c
            JOIN   pg_class      t ON c.conrelid = t.oid
            WHERE  t.relname    = 'applications'
            AND    c.contype    = 'u'
            AND    pg_get_constraintdef(c.oid) LIKE '%job_id%';

            IF _cname IS NOT NULL THEN
                EXECUTE format('ALTER TABLE applications DROP CONSTRAINT %I', _cname);
            END IF;
        END $$;
    """)

    # ── ARCH-7 step 2: partial unique indexes replacing the old constraint ────

    # Add user_id column if it doesn't exist yet
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_name = 'applications'
                AND column_name = 'user_id'
            ) THEN
                ALTER TABLE applications
                ADD COLUMN user_id UUID NULL;
            END IF;
        END $$;
    """)

    # Personal / single-user mode: one application per job when user_id IS NULL
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_job_id_personal
        ON applications (job_id)
        WHERE user_id IS NULL
    """)

    # Multi-user mode: one application per (user, job) pair
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS idx_applications_user_job_multiuser
        ON applications (user_id, job_id)
        WHERE user_id IS NOT NULL
    """)

    # ── Trigger update: point sync function at `jobs` instead of `opportunities`
    op.execute("""
        CREATE OR REPLACE FUNCTION sync_application_to_opportunity()
        RETURNS TRIGGER AS $$
        DECLARE
            v_response_status  TEXT;
            v_interview_stage  TEXT;
        BEGIN
            CASE NEW.stage
                WHEN 'replied'   THEN
                    v_response_status := 'Replied';
                    v_interview_stage := '';
                WHEN 'interview' THEN
                    v_response_status := 'Replied';
                    v_interview_stage := 'Technical';
                WHEN 'offer'     THEN
                    v_response_status := 'Replied';
                    v_interview_stage := 'Offer';
                WHEN 'rejected'  THEN
                    v_response_status := 'Rejected';
                    v_interview_stage := 'Rejected';
                ELSE
                    v_response_status := 'No response';
                    v_interview_stage := '';
            END CASE;

            -- NB: table is now `jobs`, not `opportunities`
            UPDATE jobs
            SET
                applied          = TRUE,
                response_status  = v_response_status,
                interview_stage  = v_interview_stage
            WHERE id = NEW.job_id;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # The trigger itself (trg_sync_application_to_opportunity) still references
    # the function by name, not the table — no need to recreate the trigger.


# ─────────────────────────────────────────────────────────────────────────────
# DOWNGRADE
# ─────────────────────────────────────────────────────────────────────────────

def downgrade() -> None:
    # Revert trigger to point back at `opportunities`
    op.execute("""
        CREATE OR REPLACE FUNCTION sync_application_to_opportunity()
        RETURNS TRIGGER AS $$
        DECLARE
            v_response_status  TEXT;
            v_interview_stage  TEXT;
        BEGIN
            CASE NEW.stage
                WHEN 'replied'   THEN
                    v_response_status := 'Replied';
                    v_interview_stage := '';
                WHEN 'interview' THEN
                    v_response_status := 'Replied';
                    v_interview_stage := 'Technical';
                WHEN 'offer'     THEN
                    v_response_status := 'Replied';
                    v_interview_stage := 'Offer';
                WHEN 'rejected'  THEN
                    v_response_status := 'Rejected';
                    v_interview_stage := 'Rejected';
                ELSE
                    v_response_status := 'No response';
                    v_interview_stage := '';
            END CASE;

            UPDATE opportunities
            SET
                applied          = TRUE,
                response_status  = v_response_status,
                interview_stage  = v_interview_stage
            WHERE id = NEW.job_id;

            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)

    # Drop partial indexes added by ARCH-7
    op.execute("DROP INDEX IF EXISTS idx_applications_user_job_multiuser")
    op.execute("DROP INDEX IF EXISTS idx_applications_job_id_personal")

    # Restore original UNIQUE(job_id) constraint
    op.execute("""
        ALTER TABLE applications
        ADD CONSTRAINT applications_job_id_key UNIQUE (job_id)
    """)

    # Rename indexes back to their original names
    _rename_index_if_exists("idx_jobs_score",    "idx_opp_score")
    _rename_index_if_exists("idx_jobs_applied",  "idx_opp_applied")
    _rename_index_if_exists("idx_jobs_date",     "idx_opp_date")
    _rename_index_if_exists("idx_jobs_source",   "idx_opp_source")
    _rename_index_if_exists("idx_jobs_hash",     "idx_opp_hash")
    _rename_index_if_exists("idx_jobs_unscored", "idx_opp_unscored")

    # Drop the compat view before renaming the table back
    op.execute("DROP VIEW IF EXISTS opportunities")

    # Rename table back
    op.rename_table("jobs", "opportunities")


# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _rename_index_if_exists(old_name: str, new_name: str) -> None:
    """
    Renames a Postgres index only if `old_name` exists.
    Safe to call on a freshly initialised DB that has never had these indexes.
    """
    op.execute(f"""
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE indexname = '{old_name}'
            ) THEN
                ALTER INDEX {old_name} RENAME TO {new_name};
            END IF;
        END $$;
    """)
