-- storage/schema.sql
--
-- PURPOSE:
--   Defines the complete DevSignal database structure.
--   PostgreSQL runs this automatically the first time the container starts
--   (because we mounted it in docker-compose.yml's initdb.d directory).
--
--   Safe to re-run manually — every statement uses IF NOT EXISTS
--   so it never errors if things already exist.
--
-- TABLES:
--   1. opportunities       — every iOS job discovered across all sources
--   2. companies_watchlist — iOS companies with no job posted yet
--   3. scrape_runs         — log of every automated run
--
-- PLACEMENT: storage/schema.sql


-- ═══════════════════════════════════════════════════════════════════════
-- TABLE 1: opportunities
--
-- The main table. Every job discovered by any scraper gets one row here.
-- The job_hash column prevents duplicates — same job from 2 sources = 1 row.
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS opportunities (

    -- PRIMARY KEY: auto-assigned integer, unique per row
    -- SERIAL = automatically counts up: 1, 2, 3, 4...
    -- You never set this manually — Postgres handles it
    id                  SERIAL          PRIMARY KEY,

    -- ── When and where we found it ───────────────────────────────────────
    -- TIMESTAMPTZ = timestamp with timezone, always stored as UTC
    -- DEFAULT NOW() = if not provided, use the current time
    date_found          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- Which platform this job came from (e.g. "RemoteOK", "HackerNews")
    job_source          VARCHAR(50)     NOT NULL DEFAULT '',

    -- The direct URL to apply or view the job
    apply_link          TEXT            NOT NULL DEFAULT '',

    -- MD5 fingerprint: company+role+url hashed to 32 hex characters
    -- UNIQUE means two rows can never have the same hash — enforces deduplication
    job_hash            VARCHAR(32)     NOT NULL UNIQUE,

    -- ── Job details ───────────────────────────────────────────────────────
    company             VARCHAR(200)    NOT NULL DEFAULT '',
    role                VARCHAR(300)    NOT NULL DEFAULT '',
    location            VARCHAR(200)    NOT NULL DEFAULT '',

    -- CHECK constraint enforces only these exact values are allowed
    remote              VARCHAR(10)     NOT NULL DEFAULT 'Unknown'
                            CHECK (remote IN ('Yes', 'No', 'Hybrid', 'Unknown')),

    visa_sponsorship    VARCHAR(10)     NOT NULL DEFAULT 'Unknown'
                            CHECK (visa_sponsorship IN ('Yes', 'No', 'Unknown')),

    -- e.g. "0-1 years", "Fresh graduate", "Entry level"
    experience_req      VARCHAR(100)    NOT NULL DEFAULT '',

    -- Comma-separated tech tags: "swift, swiftui, ios, xcode"
    tech_stack          TEXT            NOT NULL DEFAULT '',

    -- Raw description text (HTML stripped), capped at 1000 chars in Python
    description_raw     TEXT            NOT NULL DEFAULT '',

    -- ── Recruiter info (filled by processors/enricher.py in Phase 6) ─────
    recruiter_name      VARCHAR(200)    NOT NULL DEFAULT '',
    recruiter_role      VARCHAR(200)    NOT NULL DEFAULT '',

    -- Full LinkedIn profile URL
    linkedin_profile    TEXT            NOT NULL DEFAULT '',

    -- Discovered email address (from Hunter.io)
    email               VARCHAR(200)    NOT NULL DEFAULT '',

    -- ── AI fields (filled by ai/scorer.py in Phase 5) ────────────────────
    -- NULL means "not scored yet" — lets us query WHERE opportunity_score IS NULL
    -- SMALLINT is sufficient: scores are 0-100, max value 32767
    opportunity_score   SMALLINT
                            CHECK (opportunity_score IS NULL
                                OR (opportunity_score >= 0 AND opportunity_score <= 100)),

    -- JSONB stores the per-factor breakdown as queryable JSON
    -- Example value: {"remote": 20, "visa": 15, "swift_match": 15, ...}
    score_breakdown     JSONB,

    -- The personalized outreach message generated by the AI
    outreach_message    TEXT            NOT NULL DEFAULT '',

    -- ── Application tracking (you update these manually or via dashboard) ─
    applied             BOOLEAN         NOT NULL DEFAULT FALSE,

    response_status     VARCHAR(20)     NOT NULL DEFAULT ''
                            CHECK (response_status IN (
                                '', 'No response', 'Viewed', 'Replied', 'Rejected'
                            )),

    interview_stage     VARCHAR(20)     NOT NULL DEFAULT ''
                            CHECK (interview_stage IN (
                                '', 'Phone screen', 'Technical',
                                'Final round', 'Offer', 'Rejected'
                            )),

    -- ── Timestamps ───────────────────────────────────────────────────────
    -- updated_at is auto-maintained by the trigger defined below
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════════
-- TABLE 2: companies_watchlist
--
-- iOS companies that haven't posted an internship yet.
-- We track them so we're ready the moment they do.
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS companies_watchlist (
    id                  SERIAL          PRIMARY KEY,
    -- UNIQUE on company name — no duplicates in the watchlist
    company             VARCHAR(200)    NOT NULL UNIQUE,
    ios_product_desc    TEXT            NOT NULL DEFAULT '',
    company_url         TEXT            NOT NULL DEFAULT '',
    linkedin_url        TEXT            NOT NULL DEFAULT '',
    -- e.g. "Seed", "Series A", "Series B", "Public"
    funding_stage       VARCHAR(50)     NOT NULL DEFAULT '',
    notes               TEXT            NOT NULL DEFAULT '',
    added_at            TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ═══════════════════════════════════════════════════════════════════════
-- TABLE 3: scrape_runs
--
-- Logs every time the pipeline runs.
-- Useful for debugging ("why didn't it find anything yesterday?")
-- and for monitoring ("is it actually running every 12 hours?")
-- ═══════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS scrape_runs (
    id                  SERIAL          PRIMARY KEY,
    started_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    -- NULL until the run finishes (lets you detect stuck/crashed runs)
    finished_at         TIMESTAMPTZ,

    -- How many raw jobs came back from all scrapers combined
    jobs_found          INTEGER         NOT NULL DEFAULT 0,

    -- How many were new after deduplication
    jobs_new            INTEGER         NOT NULL DEFAULT 0,

    -- How many got AI scores applied
    jobs_scored         INTEGER         NOT NULL DEFAULT 0,

    -- Any error messages, empty string if clean run
    errors              TEXT            NOT NULL DEFAULT '',

    -- Who/what triggered this run
    triggered_by        VARCHAR(20)     NOT NULL DEFAULT 'manual'
                            CHECK (triggered_by IN ('manual', 'n8n', 'cron'))
);


-- ═══════════════════════════════════════════════════════════════════════
-- INDEXES
--
-- Indexes make queries fast. Without them, every WHERE clause
-- scans every row in the table — fine for 100 rows, slow for 100,000.
-- Think of an index like a book's index: jump straight to the page
-- instead of reading every page to find what you need.
--
-- We create indexes on columns we'll frequently filter or sort by.
-- ═══════════════════════════════════════════════════════════════════════

-- We often query: WHERE opportunity_score >= 70 ORDER BY opportunity_score DESC
CREATE INDEX IF NOT EXISTS idx_opp_score
    ON opportunities (opportunity_score DESC NULLS LAST);

-- We often query: WHERE applied = FALSE (to find what still needs action)
CREATE INDEX IF NOT EXISTS idx_opp_applied
    ON opportunities (applied);

-- We often query: WHERE date_found >= NOW() - INTERVAL '12 hours'
CREATE INDEX IF NOT EXISTS idx_opp_date
    ON opportunities (date_found DESC);

-- We often query: WHERE job_source = 'RemoteOK' (dashboard source breakdown)
CREATE INDEX IF NOT EXISTS idx_opp_source
    ON opportunities (job_source);

-- The deduplicator calls hash_exists() constantly — must be instant
-- (The UNIQUE constraint already creates an index, but naming it helps clarity)
CREATE INDEX IF NOT EXISTS idx_opp_hash
    ON opportunities (job_hash);

-- We often query: WHERE opportunity_score IS NULL (to find unscored jobs)
CREATE INDEX IF NOT EXISTS idx_opp_unscored
    ON opportunities (id) WHERE opportunity_score IS NULL;


-- ═══════════════════════════════════════════════════════════════════════
-- TRIGGER: auto-update updated_at on every row modification
--
-- A trigger is a function that Postgres calls automatically when
-- something happens. This one fires BEFORE every UPDATE on opportunities
-- and sets updated_at to the current time.
--
-- Without this, you'd have to manually set updated_at in every UPDATE
-- statement across your entire codebase — easy to forget.
-- ═══════════════════════════════════════════════════════════════════════

-- Step 1: Create the function the trigger will call
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    -- NEW refers to the row being updated (with the new values)
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Step 2: Attach the function to the table
DROP TRIGGER IF EXISTS trg_set_updated_at ON opportunities;
CREATE TRIGGER trg_set_updated_at
    BEFORE UPDATE ON opportunities
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();


-- ═══════════════════════════════════════════════════════════════════════
-- VERIFICATION QUERY
-- This runs at the end to confirm the schema applied correctly.
-- Output appears in docker compose logs postgres on first boot.
-- ═══════════════════════════════════════════════════════════════════════

DO $$
BEGIN
    RAISE NOTICE 'DevSignal schema applied successfully.';
    RAISE NOTICE 'Tables: opportunities, companies_watchlist, scrape_runs';
END $$;